"""empty message

Revision ID: 21629689a605
Revises: 150b11ca3f08
Create Date: 2023-11-27 12:44:53.327380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21629689a605'
down_revision: Union[str, None] = '150b11ca3f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('List Of Products', sa.Column('date_of_manufacture', sa.DateTime(), nullable=True))
    op.add_column('List Of Products', sa.Column('expiration_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('List Of Products', 'expiration_date')
    op.drop_column('List Of Products', 'date_of_manufacture')
    # ### end Alembic commands ###
