"""empty message

Revision ID: 150b11ca3f08
Revises: 6d9ac9554273
Create Date: 2023-11-27 12:40:46.892395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '150b11ca3f08'
down_revision: Union[str, None] = '6d9ac9554273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('List Of Products', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('List Of Products', 'user_id')
    # ### end Alembic commands ###
