"""empty message

Revision ID: a5afdbb930f5
Revises: f93719797273
Create Date: 2023-12-02 16:23:38.920510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5afdbb930f5'
down_revision: Union[str, None] = 'f93719797273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('List Of Products', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('List Of Products', 'date_of_manufacture',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('List Of Products', 'expiration_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'List Of Products', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'List Of Products', type_='foreignkey')
    op.alter_column('List Of Products', 'expiration_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('List Of Products', 'date_of_manufacture',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('List Of Products', 'user_id')
    # ### end Alembic commands ###
