"""empty message

Revision ID: f3ce1fa3cd04
Revises: 21629689a605
Create Date: 2023-11-27 12:45:53.160211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ce1fa3cd04'
down_revision: Union[str, None] = '21629689a605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('List Of Products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('List Of Products', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
