"""empty message

Revision ID: c7e1424f499e
Revises: fdd50ff951a3
Create Date: 2023-10-30 11:47:12.351580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e1424f499e'
down_revision: Union[str, None] = 'fdd50ff951a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
